<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150617/1-15061G52607.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/150617/1-15061G52607.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="829";
$z[1][4]['height']="1308";
$z[2]=Array("img"," /uploads/allimg/150617/1-15061G52607-50.jpg ",241,393);
$z[2][4]['ddimg']="/uploads/allimg/150617/1-15061G52607-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="829";
$z[2][4]['height']="1308";
$z[3]=Array("img"," /uploads/allimg/150617/1-15061G52608.jpg ",395,541);
$z[3][4]['ddimg']="/uploads/allimg/150617/1-15061G52608.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="829";
$z[3][4]['height']="1308";

?>