<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150617/1-15061G53133.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150617/1-15061G53133.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="761";
$z[1][4]['height']="578";
$z[2]=Array("img"," /uploads/allimg/150617/1-15061G53133-50.jpg ",240,391);
$z[2][4]['ddimg']="/uploads/allimg/150617/1-15061G53133-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="742";
$z[2][4]['height']="572";
$z[3]=Array("img"," /uploads/allimg/150617/1-15061G53134.jpg ",393,538);
$z[3][4]['ddimg']="/uploads/allimg/150617/1-15061G53134.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="744";
$z[3][4]['height']="549";
$z[4]=Array("img"," /uploads/allimg/150617/1-15061G53134-50.jpg ",540,691);
$z[4][4]['ddimg']="/uploads/allimg/150617/1-15061G53134-50.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="742";
$z[4][4]['height']="568";

?>