{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150617/1-15061G52J2.jpg' text='' width='740' height='3727'} /uploads/allimg/150617/1-15061G52J2.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150617/1-15061G52J2-50.jpg' text='' width='740' height='3727'} /uploads/allimg/150617/1-15061G52J2-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150617/1-15061G52J3.jpg' text='' width='740' height='3727'} /uploads/allimg/150617/1-15061G52J3.jpg {/dede:img}
