<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150617/1-15061G52911.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/150617/1-15061G52911.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="740";
$z[1][4]['height']="1088";
$z[2]=Array("img"," /uploads/allimg/150617/1-15061G52912.jpg ",241,387);
$z[2][4]['ddimg']="/uploads/allimg/150617/1-15061G52912.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="740";
$z[2][4]['height']="1088";

?>