<?php
$z[0]=Array("flink","  [field:link /]  ",715,794);
$z[0][4]['titlelen']="101";
$z[0][4]['row']="10";
$z[0][4]['type']="text";
$z[1]=Array("global","",901,923);
$z[1][4]['name']="cfg_add";
$z[2]=Array("global","",947,969);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",993,1017);
$z[3][4]['name']="cfg_email";
$z[4]=Array("global","",1041,1066);
$z[4][4]['name']="cfg_teltwo";
$z[5]=Array("global","",1081,1107);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",1119,1143);
$z[6][4]['name']="cfg_beian";

?>