<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",549,568);
$z[4][4]['name']="title";
$z[5]=Array("global","",569,595);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("include","",699,734);
$z[6][4]['filename']="head.htm";
$z[7]=Array("channel"," <a href='[field:typeurl/]'>\r\n    <li >[field:typename/]</li>\r\n    </a> ",1022,1226);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<a href='~typelink~' ~rel~> <li class='curr'>~typename~</li> </a>";
$z[8]=Array("list"," <a href=\"[field:arcurl/]\">\r\n      <div class=\"tupian\"> <img src=\"[field:picname/]\" />\r\n        <div class=\"block\"></div>\r\n        <div class=\"text\"><span>[field:title/]</span></div>\r\n      </div>\r\n      </a> ",1285,1530);
$z[8][4]['pagesize']="9";
$z[9]=Array("pagelist","",1594,1641);
$z[9][4]['listitem']="pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",1734,1771);
$z[10][4]['filename']="footer.htm";

?>