<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",549,568);
$z[4][4]['name']="title";
$z[5]=Array("global","",569,595);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("include","",699,734);
$z[6][4]['filename']="head.htm";
$z[7]=Array("type","\r\n  <h1>NEWS INFORMATION</h1>\r\n  <h2>[field:typename /]</h2>\r\n  ",794,892);
$z[7][4]['typeid']="8";
$z[8]=Array("list"," <a href=\"[field:arcurl/]\">\r\n    <div class=\"wk1\"> <img src=\"[field:picname/]\" />\r\n      <li> <span>[field:title/]</span>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</br>\r\n        [field:infos/] </li>\r\n    </div>\r\n    </a> ",1054,1329);
$z[8][4]['pagesize']="9";
$z[8][4]['infolen']="180";
$z[9]=Array("pagelist","",1392,1439);
$z[9][4]['listitem']="pageno";
$z[9][4]['listsize']="3";
$z[10]=Array("include","",1519,1556);
$z[10][4]['filename']="footer.htm";

?>