<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",559,594);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",625,646);
$z[5][4]['name']="content";
$z[6]=Array("include","",677,714);
$z[6][4]['filename']="footer.htm";

?>